### ISSUE TITLE
Decompressed data don't match the original

### ISSUE THREAD

**Issue by vasiliyeskin** [byronknoll/tensorflow-compress#2] opened 2021-08-12 15:35 UTC
Current version of the tensorflow-compress (https://colab.research.google.com/github/byronknoll/tensorflow-compress/blob/master/tensorflow-compress.ipynb#scrollTo=ZUc1x3vIs4hF) outputs after compression and decompression of data enwik4 (or enwik5) that does not match the original. All settings are default except 'path_to_file'. 
May be I am doing something wrong or settings of Colab were changed?

**Comment by byronknoll** [comment] 2021-08-13 17:29
Thanks. Yes, this looks like a bug. I have just reproduced the issue myself. I think this was working before. My current theory is that this is due to GPU non-determinism. When I switch to running on CPU (with a much smaller network size to make it fast) the decompression matches.

**Comment by byronknoll** [comment] 2021-08-21 06:55
Actually, I just tried testing this again and it seems to be working for me now. Maybe some bug was recently fixed in some library dependency? Anyway, it would be great if you could also confirm it works, and then I can close this issue.

**Comment by vasiliyeskin** [comment] 2021-08-23 05:20
Dear Byron, 

I have checked the tensorflow-compress calculations on Colab and the local machine with the GPU accelerators. Now md5sums of the 'enwik4' origin and compressed-decompressed files are matched.

**Closed as completed** 2021-08-23 16:04 UTC
